[package]
name = "mon-rober"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.2"
image = "0.24.7"
walkdir = "2.3.3"
